# Generated by Django 5.1.1 on 2024-12-14 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GreenPlan', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GreenPlan',
            new_name='GreenPlan',
        ),
        migrations.CreateModel(
            name='GreenSubscribedUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_phone_number', models.CharField(max_length=15)),
                ('subscription_start_date', models.DateTimeField()),
                ('subscription_end_date', models.DateTimeField()),
                ('g_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GreenPlan.greenplan')),
            ],
        ),
    ]
