# Generated by Django 3.1.6 on 2021-02-17 02:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_auto_20210217_0333'),
    ]

    operations = [
        migrations.CreateModel(
            name='فرع',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('الاسم', models.CharField(max_length=50)),
                ('الرصيد', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterModelOptions(
            name='حساب',
            options={'verbose_name_plural': 'حساب'},
        ),
        migrations.CreateModel(
            name='موظف',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('الفرع', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.فرع')),
                ('المستخدم', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='شحن',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('المبلغ', models.IntegerField(default=0)),
                ('الفرع', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.فرع')),
                ('لصالح', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='سحب',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('المبلغ', models.IntegerField(default=0)),
                ('الفرع', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.فرع')),
                ('لصالح', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='تحويل',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('المبلغ', models.IntegerField(default=0)),
                ('إلى', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='تحويل_داخل', to=settings.AUTH_USER_MODEL)),
                ('من', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='تحويل_خارج', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
