# Generated by Django 3.1.6 on 2021-02-17 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210217_0449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='حساب',
            name='الرصيد',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='سحب',
            name='المبلغ',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='شحن',
            name='المبلغ',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='فرع',
            name='الرصيد',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
