apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: internship2024
  name: kalimatcash-internship2024-pvc
  labels:
    type: local
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 0.1Gi
  volumeName: kalimatcash-internship2024-pv
  storageClassName: standard
