apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: internship2024
  name: kalimatcash-internship2024-pv
  labels:
    type: local
spec:
  capacity:
    storage: 0.1Gi
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/kalimatcash-internship2024-pv"
