# Generated by Django 5.1.1 on 2024-10-05 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SubscriptionPlan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='name',
            field=models.CharField(choices=[('Standard', 'Standard'), ('Plus', 'Plus'), ('Premium', 'Premium')], max_length=10, unique=True),
        ),
    ]
