# Generated by Django 5.1.1 on 2024-12-14 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SubscriptionPlan', '0004_alter_subscriptionplan_max_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanSubscribedUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_phone_number', models.CharField(max_length=15)),
                ('subscription_start_date', models.DateTimeField()),
                ('subscription_end_date', models.DateTimeField()),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SubscriptionPlan.subscriptionplan')),
            ],
        ),
    ]
