# Generated by Django 5.1.1 on 2024-09-29 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('GreenUser', '0001_initial'),
        ('SubscriptionPlan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('green_user_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='GreenUser.greenuser')),
                ('subscription_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='SubscriptionPlan.subscriptionplan')),
            ],
        ),
    ]
