apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: internship2024
  name: rabbit-internship2024-kalimatcash-pvc
  labels:
    type: local
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  volumeName: rabbit-internship2024-kalimatcash-pv
  storageClassName: standard
