# Generated by Django 5.1.1 on 2024-10-02 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0002_wallet_is_active_deletedwallets'),
    ]

    operations = [
        migrations.AddField(
            model_name='deletedwallets',
            name='deletion_confirmation',
            field=models.BooleanField(default=False),
        ),
    ]
