# Generated by Django 5.1.1 on 2024-10-02 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0003_deletedwallets_deletion_confirmation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deletedwallets',
            name='final_deletion_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
