# Generated by Django 5.1.1 on 2024-10-06 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0004_alter_deletedwallets_final_deletion_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
