# Generated by Django 5.1.1 on 2024-09-29 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('receiver', models.CharField(max_length=15)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fees', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('service_type', models.CharField(choices=[('Deposit', 'deposit'), ('Withdrawal', 'withdrawal'), ('Transaction', 'transaction'), ('Bill Payment', 'bill payment'), ('Merchant Payment', 'merchant payment'), ('Account Subscription', 'account subscription'), ('Green Subscription', 'green subscription')], max_length=50, null=True)),
                ('service_name', models.CharField(blank=True, max_length=50, null=True)),
                ('balance_before', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('balance_after', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sender', to='users.user')),
                ('user_wallet', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_wallet', to='wallets.wallet')),
            ],
        ),
    ]
